version: 2.1

executors:
  normal_container:
    docker:
      - image: cimg/python:3.11

jobs:
  build1:
    executor: normal_container
    steps:
      - checkout
      - run:
          name: build1
          command: |
            echo $message

  build2:
    executor: normal_container
    steps:
      - checkout
      - run:
          name: build2
          command: |
            echo $message

workflows:
  build_and_test:
    jobs:
      - build1:
          context:
            - english
            - japanese

      - build2:
          context:
            - japanese
            - english
